stages:
    - precompile
    - test
    - benchmark


default:
    tags: [ "downscope" ]

.julia-job:
    variables:
        SLURM_PARAM_ACCOUNT: "-A thes1464"
        SLURM_PARAM_TASKS: "-n 1"
        SLURM_PARAM_CPUS: "--cpus-per-task=24"
        SLURM_PARAM_TIME: "-t 01:00:00"
    before_script:
        - source /work/co693196/MA/julia.sh

precompile-job:
    extends: .julia-job
    stage: precompile
    script:
        - mkdir run
        - cd run
        - $JULIA_EXEC --project="." -e 'using Pkg; Pkg.develop(PackageSpec(path=".."))'

.test-job:
    extends: .julia-job
    stage: test
    before_script:
        - source /work/co693196/MA/julia.sh
        - mkdir run
        - cd run
        - $JULIA_EXEC --project="." -e 'using Pkg; Pkg.add(["OrdinaryDiffEq", "KernelAbstractions"]); Pkg.develop(PackageSpec(path=".."));'

.benchmark-job:
    extends: .julia-job
    stage: benchmark
    before_script:
        - source /work/co693196/MA/julia.sh
        - mkdir run
        - cd run
        - $JULIA_EXEC --project="." -e 'using Pkg; Pkg.add(["OrdinaryDiffEq", "KernelAbstractions", "BenchmarkTools"]); Pkg.develop(PackageSpec(path=".."));'

cpu-test-job:
    extends: .test-job
    script:
        - $JULIA_EXEC --project="." --threads=24 -e 'using Trixi; trixi_include(pkgdir(Trixi, "test", "test_tree_2d_advection.jl"), offload=false)'

cpu-offload-test-job:
    extends: .test-job
    script:
        - $JULIA_EXEC --project="." --threads=24 -e 'using Trixi; trixi_include(pkgdir(Trixi, "test", "test_tree_2d_advection.jl"), offload=true)'

gpu-offload-test-job:
    extends: .test-job
    variables:
        SLURM_PARAM_GPUS: "--gres=gpu:volta:1"
        SLURM_PARAM_PARTITION: "--partition=c18g"
    script:
        - $JULIA_EXEC --project="." --threads=24 -e 'using Pkg; Pkg.add("CUDA")'
        - $JULIA_EXEC --project="." --threads=24 -e 'using Trixi, CUDA; using CUDA.CUDAKernels; trixi_include(pkgdir(Trixi, "test", "test_tree_2d_advection.jl"), offload=true, backend=CUDABackend())'

cpu-benchmark-job:
    extends: .benchmark-job
    script:
        - $JULIA_EXEC --project="." --threads=24 -e 'using Trixi, BenchmarkTools; display(@benchmark trixi_include($joinpath(examples_dir(), "tree_2d_dgsem", "elixir_advection_basic.jl"), offload=false))'

cpu-offload-benchmark-job:
    extends: .benchmark-job
    script:
        - $JULIA_EXEC --project="." --threads=24 -e 'using Trixi, BenchmarkTools; display(@benchmark trixi_include($joinpath(examples_dir(), "tree_2d_dgsem", "elixir_advection_basic.jl"), offload=true))'

gpu-offload-benchmark-job:
    extends: .benchmark-job
    variables:
        SLURM_PARAM_GPUS: "--gres=gpu:volta:1"
        SLURM_PARAM_PARTITION: "--partition=c18g"
    script:
        - $JULIA_EXEC --project="." --threads=24 -e 'using Pkg; Pkg.add("CUDA")'
        - $JULIA_EXEC --project="." --threads=24 -e 'using Trixi, CUDA, CUDA.CUDAKernels, BenchmarkTools; display(@benchmark trixi_include($joinpath(examples_dir(), "tree_2d_dgsem", "elixir_advection_basic.jl"), offload=true, backend=CUDABackend()))'